-- --------------------------------------------------------------
-- Tarea 06: Bases de Datos MySQL
-- Estructuras Abstractas de Datos y Algoritmos para Ingeniería
-- Kristhel Quesada Lopez, C06153
-- Script con el flujo de desarrollo implementado.
-- --------------------------------------------------------------

-- Creacion de la base de datos
CREATE SCHEMA `Tarea06_db`;

-- Creacion de las tablas y relaciones de la base de datos mediante
-- la herramienta propia de MySQL Workbench para la creacion de modelos
-- MySQL Script generated by MySQL Workbench
-- dom 09 jun 2024 23:38:10 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Tarea06_db` DEFAULT CHARACTER SET utf8 ;
USE `Tarea06_db` ;

-- -----------------------------------------------------
-- Table `Tarea06_db`.`Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tarea06_db`.`Cursos` (
  `id_curso` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sigla` CHAR(7) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `semestre` VARCHAR(4) DEFAULT NULL,
  `creditos` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_curso`),
  UNIQUE INDEX `sigla_UNIQUE` (`sigla` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  UNIQUE INDEX `id_curso_UNIQUE` (`id_curso` ASC) VISIBLE,
  INDEX `semestre_idx` (`semestre` ASC) VISIBLE,
  INDEX `creditos_idx` (`creditos` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea06_db`.`Requisitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tarea06_db`.`Requisitos` (
  `id_requisitos` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_curso` INT UNSIGNED NOT NULL,
  `id_curso_requisito` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_requisitos`),
  INDEX `rqm_curso_idx` (`id_curso_requisito` ASC) VISIBLE,
  UNIQUE INDEX `id_requisitos_UNIQUE` (`id_requisitos` ASC) VISIBLE,
  INDEX `curso_idx` (`id_curso` ASC) VISIBLE,
  CONSTRAINT `fk_id_curso_rqm`
    FOREIGN KEY (`id_curso`)
    REFERENCES `Tarea06_db`.`Cursos` (`id_curso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_curso_requisito_rqm`
    FOREIGN KEY (`id_curso_requisito`)
    REFERENCES `Tarea06_db`.`Cursos` (`id_curso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea06_db`.`Descripciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tarea06_db`.`Descripciones` (
  `id_descripcion` INT NOT NULL,
  `id_curso` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT NOT NULL,
  `dificultad` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`id_descripcion`),
  INDEX `fk_descripcion_idx` (`id_curso` ASC) VISIBLE,
  UNIQUE INDEX `id_descripcion_UNIQUE` (`id_descripcion` ASC) VISIBLE,
  UNIQUE INDEX `id_curso_UNIQUE` (`id_curso` ASC) VISIBLE,
  FULLTEXT INDEX `descripcion` (`descripcion`) VISIBLE,
  INDEX `dificultad` (`dificultad` ASC) VISIBLE,
  CONSTRAINT `fk_curso_described`
    FOREIGN KEY (`id_curso`)
    REFERENCES `Tarea06_db`.`Cursos` (`id_curso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Modificacion intermedia para que los cursos optativos no tengan
-- semestre asociado. Segunda modificacion para incrementos automaticos
-- en los identificadores.
ALTER TABLE `Tarea06_db`.`Cursos`
MODIFY COLUMN semestre CHAR(2) DEFAULT NULL;

ALTER TABLE `Tarea06_db`.`Cursos`
MODIFY COLUMN id_curso INT UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE `Tarea06_db`.`Descripciones`
MODIFY COLUMN id_descripcion INT UNSIGNED NOT NULL AUTO_INCREMENT;

-- Insercion de Datos
-- Primero cursos del programa
INSERT INTO `Tarea06_db`.Cursos(sigla, nombre, semestre, creditos)
VALUE("IE-0579", "Administracion de sistemas", "IX", 4),
	 ("IE-0613", "Electronica Industrial", "IX", 4),
     ("IE-0599", "Anteproyecto de TFG", "IX", 4),
     ("IE-0679", "Ciencia de datos para la est. y pron. de eventos", "X", 3),
     ("IE-0541", "Seguridad ocupacional", "X", 3);

-- Verificacion intermedia
SELECT * FROM `Tarea06_db`.Cursos;

-- Luego cursos optativos
INSERT INTO `Tarea06_db`.Cursos(sigla, nombre, creditos)
VALUE("IE-0117", "Programacion bajo plataformas abiertas", 3),
	 ("IE-0217", "Estructuras abstractas de datos y algoritmos para ingeniería", 3),
     ("IE-0365", "Transmision de potencia", 3),
     ("IE-0414", "Control y simulacion de convertidores electronicos de potencia", 3),
     ("IE-0417", "Disenio de software para ingenieria", 3),
     ("IE-0432", "Laboratorio de control automatico", 3),
     ("IE-0433", "Instrumentacion industrial", 3),
     ("IE-0435", "Inteligencia artificial aplicada a la ingenieria electrica", 3),
     ("IE-0445", "Metrologia en la ingenieria electrica", 3),
     ("IE-0447", "Procesamiento digital de seniales I", 3),
     ("IE-0457", "Conservacion de energia electrica", 3),
     ("IE-0461", "Centrales y subestaciones", 3),
     ("IE-0465", "Redes de distribucion y transmision", 3),
     ("IE-0467", "Distribucion electrica y subterranea", 3),
     ("IE-0469", "Sistemas de potencia I", 3),
     ("IE-0471", "Disenio electrico industrial I", 3),
     ("IE-0505", "Tecnicas de optimizacion", 3),
     ("IE-0509", "Sistemas no lineales", 3),
     ("IE-0514", "Electronica de potencia y control de maquinas", 3),
     ("IE-0545", "Mediciones ópticas", "3"),
	 ("IE-0559", "Energía solar fotovoltáica", "3"),
	 ("IE-0563", "Diseño de sistemas de iluminación", "3"),
	 ("IE-0565", "Ingeniería de alta tensión", "3"),
	 ("IE-0569", "Sistemas de potencia II", "3"),
	 ("IE-0571", "Diseño eléctrico industrial II", "3"),
	 ("IE-0573", "Diseño de sistemas de señales en edificaciones", "3"),
	 ("IE-0614", "Control e integración a la red de sistemas de generación eólica", "3"),
	 ("IE-0619", "Control eléctrico industrial", "3"),
	 ("IE-0621", "Verificación funcional del diseño de circuitos integrados", "3"),
	 ("IE-0633", "Automatización industrial", "3"),
	 ("IE-0715", "Máquinas eléctricas III", "3"),
	 ("IE-0731", "Sistemas en tiempo discreto", "3"),
	 ("IE-0733", "Control distribuido", "3"),
	 ("IE-0769", "Protección del sistema de potencia", "3"),
	 ("IE-0869", "Subestaciones", "3"),
	 ("IE-1103", "Temas especiales II en ingeniería", "3"),
	 ("IE-1114", "Temas especiales II en control", "3"),
	 ("IE-1117", "Temas especiales II en máquinas eléctricas", "3"),
	 ("IE-1118", "Temas especiales II en sistemas de potencia", "3"),
	 ("IE-1169", "Sobrevoltajes y coordinación de aislamiento", "3"),
     ("IE-0321", "Estructuras de computadores digitales I", "3"),
	 ("IE-0407", "Electromagnetismo II", "3"),
	 ("IE-0437", "Fotónica", "3"),
	 ("IE-0439", "Optoelectrónica", "3"),
	 ("IE-0449", "Visión por computador", "3"),
	 ("IE-0521", "Estructuras de computadoras digitales II", "3"),
	 ("IE-0523", "Circuitos digitales II", "3"),
	 ("IE-0537", "Radiometría y fotometría", "3"),
	 ("IE-0623", "Microprocesadores", "3"),
	 ("IE-0624", "Laboratorio de microcontroladores", "3"),
	 ("IE-0724", "Laboratorio de programación y microcomputadores", "3"),
	 ("IE-1116", "Temas especiales II en electrónica", "3"),
	 ("IE-1119", "Temas especiales II en sistemas digitales", "3"),
	 ("IE-0425", "Redes de computadores", "3"),
	 ("IE-0527", "Ingeniería de comunicaciones", "3"),
	 ("IE-0528", "Laboratorio de transmisión de datos", "3"),
	 ("IE-0529", "Sistemas móviles en comunicaciones", "3"),
	 ("IE-0530", "Laboratorio de telecomunicaciones", "3"),
	 ("IE-0539", "Comunicaciones por fibra óptica", "3"),
	 ("IE-0627", "Conmutación telefónica", "3"),
	 ("IE-0628", "Laboratorio de microondas", "3"),
	 ("IE-0629", "Sistemas de comunicación", "3"),
	 ("IE-0639", "Circuitos integrados fotónicos", "3"),
	 ("IE-0727", "Ingeniería de radio", "3"),
	 ("IE-0729", "Redes telefónicas", "3"),
	 ("IE-0739", "Redes ópticas en telecomunicaciones", "3"),
	 ("IE-0827", "Sistemas de transmisión en telecomunicaciones", "3"),
	 ("IE-0829", "Teoría de tráfico", "3"),
	 ("IE-1115", "Temas especiales II en telecomunicaciones", "3");
     
-- Verificacion intermedia
SELECT * FROM `Tarea06_db`.Cursos;

-- Tras la verificacion, debido a que hubo un fallo de insercion porque se repitio
-- un curso, entonces el autoincrement paso de 5 a 76, entonces se va a intentar
-- arreglar esto haciendo una tabla temporal para probar que la logica funciona.
-- Luego se realizan los cambios en la tabla real, todo con el fin de evitar posibles
-- alteraciones no deseadas a la tabla real

CREATE TEMPORARY TABLE test SELECT id_curso FROM `Tarea06_db`.Cursos LIMIT 10;
SELECT * FROM `Tarea06_db`.test;
DROP TEMPORARY TABLE test; -- no se agarraron los datos desde el uno, entonces se prueba de nuevo
CREATE TEMPORARY TABLE test SELECT id_curso FROM `Tarea06_db`.Cursos ORDER BY id_curso LIMIT 10;
SELECT * FROM `Tarea06_db`.test;

-- Todo bien por el momento, entonces se procede a intentar modificar los incrementos
-- Se me generaba el siguiente error al ejecutar
-- 		UPDATE `Tarea06_db`.test SET id_curso = id_curso - 70 WHERE id_curso > 5;
-- Error Code: 1175. You are using safe update mode and you tried to update a table without
-- a WHERE that uses a KEY column.  To disable safe mode, toggle the option in Preferences 
-- -> SQL Editor and reconnect.

-- Se concluye que el where estaba presente pero se estaba segiro del KEY, por ende se consulta
SHOW KEYS FROM `Tarea06_db`.test WHERE Key_name = 'PRIMARY';
-- como no hubo resultados entonces quiere decir que id_curso no es key value, entonces hay dos
-- soluciones.

-- 1. Apagar el safe mode y volverlo a activar
SET SQL_SAFE_UPDATES = 0;
UPDATE `Tarea06_db`.test
SET id_curso = id_curso + 70
WHERE id_curso > 5;
SET SQL_SAFE_UPDATES = 1;
SELECT * FROM `Tarea06_db`.test;

-- 2. Por seguridad, mejor hacer id_curso key value y ejecutar
ALTER TABLE `Tarea06_db`.test
ADD PRIMARY KEY (id_curso);

UPDATE `Tarea06_db`.test
SET id_curso = id_curso - 70
WHERE id_curso > 5;
SELECT * FROM `Tarea06_db`.test;

-- Se comprueba el exito del prueba, entonces eliminamos la tabla
-- temporal y actuamos sobre la real. En este caso restamos 70
-- por como quedo convenientemente el indice interrumpido
DROP TEMPORARY TABLE test;
UPDATE `Tarea06_db`.Cursos
SET id_curso = id_curso - 70
WHERE id_curso > 5;
SELECT * FROM `Tarea06_db`.Cursos;

-- Modificacion intermedia para el semestre char(2) -> varchar(4)
ALTER TABLE `Tarea06_db`.`Cursos`
MODIFY COLUMN semestre VARCHAR(4) DEFAULT NULL;

-- Ahora se agregan los cursos de prerequisitos
-- hubo error de insercion por valores repetidos, para que no pase lo de arriba
-- es decir un corrimiento en el autoincremento verificamos donde esta y setteamos
-- previamente
SELECT AUTO_INCREMENT
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = 'Tarea06_db'
AND TABLE_NAME = 'Cursos'; -- dice que 165 corroboremos agregando un curso

INSERT INTO `Tarea06_db`.Cursos(sigla, nombre, semestre, creditos)
VALUE("IE-0479", "Ingenieria economica", "VIII", 3);
SELECT * FROM `Tarea06_db`.Cursos; -- se confirma, entonces cambiamos ese y modificamos para los siguientes

UPDATE `Tarea06_db`.Cursos
SET id_curso = id_curso - 90
WHERE id_curso > 74;
SELECT * FROM `Tarea06_db`.Cursos;
ALTER TABLE `Tarea06_db`.Cursos AUTO_INCREMENT = 76;

-- probamos
INSERT INTO `Tarea06_db`.Cursos(sigla, nombre, semestre, creditos)
VALUE("IE-0413", "Electronica II", "V", 3);
SELECT * FROM `Tarea06_db`.Cursos; -- funciona, entonces agregamos los siguientes

INSERT INTO `Tarea06_db`.Cursos(sigla, nombre, semestre, creditos)
VALUE("IE-0499", "Proyecto electrico", "VIII", 3),
     ("IE-0405", "Modelos probabilísticos de señales y sistemas", "VI", 3),
     ("IE-0501", "Responsabilidades en el ejercicio profesional", "VI", 1),
     ("CI-0202", "Principios de Informatica", "II", 4),
     ("IE-0431", "Sistemas de control", "VII", 3),
     ("IE-0347", "Señales y Sistemas II", "V", 3),
     ("IE-0307", "Electromagnetismo I", "V", 3),
     ("IE-0308", "Laboratorio de electronica I", "V", 3),
     ("IE-0315", "Maquinas electricas I", "VI", 3),
     ("IE-0316", "Lab. Maquinas electricas I", "VI", 3),
     ("IE-0615", "Maquinas electricas II", "VII", 4),
     ("IE-0616", "Lab. Maquinas electricas II", "VII", 1),
     ("IE-0323", "Circuitos digitales I", "", 3),
     ("IE-0247", "Señales y Sistemas I", "IV", 3),
     ("IE-0408", "Laboratorio de electronica II", "VI", 3);
     
-- me falto agregarle el semestre a Digitales I
UPDATE `Tarea06_db`.Cursos
SET semestre = "V"
WHERE id_curso = 89;
SELECT * FROM `Tarea06_db`.Cursos;

-- Todos los cursos estan ingresados, vamos a agregarle los datos a las demas tablas
-- Primero vamos a hacer la tabla de Requisitos (solo se le agregaran a los optativos
-- y cursos propios de la carrera de licenciatura, es decir, no se agregaran los pre-
-- requisitos de los requisitos) 
INSERT INTO `Tarea06_db`.Requisitos(id_curso, id_curso_requisito)
VALUE(1, 75), (2, 76), (2, 85), (3, 77),
	 (4, 78), (4, 1), (5, 79), (6, 80),
     (7, 6), (9, 76), (10, 7), (11, 81),
     (12, 81), (13, 80), (13, 82), (14, 83),
     (14, 84), (15, 82), (15, 76), (16, 85),
     (16, 86), (17, 87), (17, 88), (18, 8),
     (19, 83), (19, 85), (19, 86), (20, 8),
     (20, 87), (20, 88), (21, 85), (21, 86),
     (22, 82), (23, 81), (24, 76), (24, 85),
     (24, 86), (25, 83), (25, 84), (26, 85),
     (26, 86), (27, 21), (28, 20), (29, 20),
     (30, 21), (31, 21), (32, 81), (32, 87),
     (32, 88), (33, 89), (34, 52), (35, 89),
     (35, 81), (36, 87), (36, 88), (37, 81),
     (38, 81), (39, 8), (40, 8), (41, 77),
     (42, 81), (43, 87), (43, 88), (44, 8),
     (45, 8), (46, 89), (47, 83), (48, 83),
     (48, 84), (49, 83), (49, 84), (50, 90),
     (51, 46), (52, 89), (53, 83), (53, 84),
     (54, 46), (55, 84), (55, 89), (55, 76),
     (56, 46), (57, 76), (58, 46), (59, 46),
     (59, 60), (60, 83), (60, 78), (61, 60),
     (62, 60), (63, 60), (64, 83), (64, 84),
     (65, 60), (66, 83), (66, 91), (67,60),
     (68, 83), (68, 84), (69, 60), (70, 60),
     (71, 83), (71, 84), (72, 60), (73, 60), (74, 60);
SELECT * FROM `Tarea06_db`.Requisitos;

-- Ahora la tabla de descripciones. No se realizan para los cursos que son
-- prerequisito de los cursos de licenciatura y optativos, porque no son del
-- plan de licenciatura.
INSERT INTO `Tarea06_db`.Descripciones(id_curso, descripcion, dificultad)
VALUE(1, "", ""),
     (2, "", ""),
     (3, "", ""),
     (4, "", ""),
     (5, "", ""),
     (6, "", ""),
     (7, "", ""),
     (8, "", ""),
     (9, "", ""),
     (10, "", ""),
     (11, "", ""),
     (12, "", ""),
     (13, "", ""),
     (14, "", ""),
     (15, "", ""),
     (16, "", ""),
     (17, "", ""),
     (18, "", ""),
     (19, "", ""),
     (20, "", ""),
     (21, "", ""),
     (22, "", ""),
     (23, "", ""),
     (24, "", ""),
     (25, "", ""),
     (26, "", ""),
     (27, "", ""),
     (28, "", ""),
     (29, "", ""),
     (30, "", "");
     
     
     
     
-- ----------------------------------------------------------------
--             Reestructuracion de la base de datos
-- ----------------------------------------------------------------

-- 1.1. Agregar la opcion ON DELETE CASCADE para las foreign keys de Requisitos
ALTER TABLE `Tarea06_db`.Requisitos
ADD CONSTRAINT fk_id_curso_rqm
FOREIGN KEY (id_curso)
REFERENCES `Tarea06_db`.Cursos(id_curso)
ON DELETE CASCADE;

ALTER TABLE `Tarea06_db`.Requisitos
ADD CONSTRAINT fk_id_curso_requisito_rqm
FOREIGN KEY (id_curso_requisito)
REFERENCES `Tarea06_db`.Cursos(id_curso)
ON DELETE CASCADE;

ALTER TABLE `Tarea06_db`.Requisitos DROP FOREIGN KEY fk_curso;
ALTER TABLE `Tarea06_db`.Requisitos DROP FOREIGN KEY fk_rqm_curso;

-- 1.2. Agregar la opcion ON DELETE CASCADE para las foreign keys de Descripciones
ALTER TABLE `Tarea06_db`.Descripciones
ADD CONSTRAINT fk_curso_described
FOREIGN KEY (id_curso)
REFERENCES `Tarea06_db`.Cursos(id_curso)
ON DELETE CASCADE;

ALTER TABLE `Tarea06_db`.Descripciones DROP FOREIGN KEY fk_descripcion;

-- 2. Eliminar todos los datos de la base de datos
DELETE FROM `Tarea06_db`.Cursos 
WHERE id_curso > 0;

-- Verificamos que se hayan eliminado los cursos
-- Verificamos que se hayan eliminado los records dependientes de las demas tablas
SELECT * FROM `Tarea06_db`.Cursos;
SELECT * FROM `Tarea06_db`.Requisitos;
SELECT * FROM `Tarea06_db`.Descripciones;

SHOW TABLES;

-- ----------------------------------------------------------------
--                   Insercion de Datos 
-- ----------------------------------------------------------------
-- 0. Actualizar los auto increments
ALTER TABLE `Tarea06_db`.Cursos AUTO_INCREMENT = 16;
ALTER TABLE `Tarea06_db`.Descripciones AUTO_INCREMENT = 1;
ALTER TABLE `Tarea06_db`.Requisitos AUTO_INCREMENT = 1;

-- 1.1. Agregar los cursos de licenciatura (Main)
INSERT INTO `Tarea06_db`.Cursos(sigla, nombre, semestre, creditos)
VALUES("IE-0579", "Administracion de sistemas", "IX", 4),
	  ("IE-0613", "Electronica Industrial", "IX", 4),
      ("IE-0599", "Anteproyecto de TFG", "IX", 4),
      ("IE-XXXX", "Optativa I", "IX", 3),
      ("IE-YYYY", "Optativa II", "IX", 3),
      ("IE-0679", "Ciencia de datos para la est. y pron. de eventos", "X", 3),
      ("IE-0541", "Seguridad ocupacional", "X", 3),
      ("IE-ZZZZ", "Optativa III", "IX", 3),
      ("IE-WWWW", "Optativa IV", "IX", 3);
      
-- 1.2. Agregar los cursos requisito del plan de licenciatura original
INSERT INTO `Tarea06_db`.Cursos(sigla, nombre, semestre, creditos)
VALUES("IE-0479", "Ingenieria economica", "VIII", 3),
	  ("IE-0315", "Maquinas Electricas I", "VI", 4),
	  ("IE-0413", "Electronica II", "V", 3),
      ("IE-0499", "Proyecto electrico", "VIII", 3),
      ("IE-0405", "Modelos probabilísticos de señales y sistemas", "VI", 3),
      ("IE-0501", "Responsabilidades en el ejercicio profesional", "VI", 1);
      
SELECT * FROM `Tarea06_db`.Cursos;


-- 2. Agregar la informacion correpospondiente a la Tabla de Requisitos
-- ... no se agregan los requisitos de requisitos
INSERT INTO `Tarea06_db`.Requisitos(id_curso, id_curso_requisito)
VALUES ((SELECT id_curso FROM `Tarea06_db`.Cursos WHERE nombre="Administracion de sistemas"), 
		(SELECT id_curso FROM `Tarea06_db`.Cursos WHERE nombre="Ingenieria economica")),
       ((SELECT id_curso FROM `Tarea06_db`.Cursos WHERE nombre="Electronica Industrial"), 
		(SELECT id_curso FROM `Tarea06_db`.Cursos WHERE nombre="Electronica II")),
       ((SELECT id_curso FROM `Tarea06_db`.Cursos WHERE nombre="Electronica Industrial"), 
		(SELECT id_curso FROM `Tarea06_db`.Cursos WHERE nombre="Maquinas Electricas I")),
       ((SELECT id_curso FROM `Tarea06_db`.Cursos WHERE nombre="Anteproyecto de TFG"), 
		(SELECT id_curso FROM `Tarea06_db`.Cursos WHERE nombre="Proyecto electrico")),
       ((SELECT id_curso FROM `Tarea06_db`.Cursos WHERE nombre="Ciencia de datos para la est. y pron. de eventos"), 
		(SELECT id_curso FROM `Tarea06_db`.Cursos WHERE nombre="Modelos probabilísticos de señales y sistemas")),
       ((SELECT id_curso FROM `Tarea06_db`.Cursos WHERE nombre="Seguridad ocupacional"), 
		(SELECT id_curso FROM `Tarea06_db`.Cursos WHERE nombre="Responsabilidades en el ejercicio profesional"));
SELECT * FROM `Tarea06_db`.Requisitos;


-- 3. Agregar la informacion correpospondiente a la Tabla de Descripciones
-- no se agrega descripcion a las Optativas I, II, III y IV
INSERT INTO `Tarea06_db`.Descripciones (id_curso, descripcion, dificultad)
VALUES
    (1,
     "En este curso, se considerará la organización o empresa como la unidad de estudio, 
      sobre la cual se desarrollará el análisis de factores internos y externos tales como 
      geopolítica, evolución tecnológica, globalización de mercados, cambios económicos, 
      transformaciones del mercado, papel del estado, y otros, aspectos que gravitan en el 
      adecuado accionar de estos sistemas.",
     "Facil"),
    (2, 
     "El curso de Electrónica de Potencia introduce los principios fundamentales y aplicaciones
      de los convertidores electrónicos, abordando desde los convertidores DC-DC con análisis 
      detallado de modos de conducción y pérdidas, hasta transformadores AC-AC y semiconductores 
      de potencia actuales. También cubre conceptos esenciales como la transmisión de energía, 
      el factor de potencia y la mitigación de corrientes armónicas, junto con el diseño y 
      funcionamiento de diversos tipos de rectificadores monofásicos y trifásicos, incluyendo los 
      controlados y los de modulación de ancho de pulso (PWM).", 
     "Medio"),
    (3, 
     "El curso de Anteproyecto de Tesis es un curso orientado a desarrollar en el estudiante las 
      habilidades necesarias para elaborar su propuesta de investigación.", 
     "Facil"),
    (6,
     "El curso de Integración Profesional en Ingeniería Eléctrica combina conocimientos previos 
      con nuevas herramientas para el análisis sistemático de eventos. Incluye optimización, 
      ciencia de datos con técnicas de preprocesamiento y extracción de características, métodos 
      computacionales como K-Means y máquinas de soporte vectorial, análisis de componentes 
      principales, árboles de decisión, pronóstico cualitativo y cuantitativo, modelos de series 
      de tiempo, probabilidad y estadística, detección de señales y pruebas de hipótesis, preparando 
      a los estudiantes con habilidades avanzadas para su desarrollo profesional en ingeniería eléctrica.",
     "Dificil"),
    (7,
     "El curso sobre Salud y Seguridad Ocupacional cubre una variedad de temas esenciales para 
      garantizar ambientes laborales seguros y saludables. Incluye la normativa sobre hostigamiento 
      sexual (Ley 7476-31-8-2020), fundamentos de salud ocupacional, conceptos clave como riesgos 
      del trabajo y seguridad industrial, así como la prevención de riesgos físicos, químicos, 
      biológicos y ergonómicos. También se abordan temas como accidentes laborales, enfermedades 
      ocupacionales, y normativas específicas como las Normas OHSAS 45000 y el reglamento de seguridad 
      en la construcción.",
     "Facil"),
    (10,
     "El curso introductorio abarca los fundamentos de la teoría microeconómica y macroeconómica, 
      con enfoque en metodologías y herramientas clave. Está dirigido a estudiantes sin experiencia 
      previa en economía, ingeniería económica o evaluación de proyectos. Se centra en desarrollar 
      habilidades para la toma de decisiones en inversiones privadas o públicas, y explora la 
      Evaluación Social de proyectos como instrumento para la gestión eficiente de recursos públicos. 
      Al finalizar, los estudiantes podrán preparar y evaluar proyectos con una comprensión del mercado 
      nacional e internacional y sus tendencias futuras.",
     "Facil"),
    (11,
     "El curso pretende familiarizar a los estudiantes, con las máquinas eléctricas estacionarias y 
      giratorias, que se encuentran en la industria y en los sistemas eléctricos de potencia. Para tal 
      efecto, se hace énfasis en el análisis en régimen permanente, de los transformadores eléctricos 
      de potencia, y las máquinas de inducción trifásicas.",
     "Medio"),
    (12,
     "Éste es un curso de electrónica analógica muy basado en el análisis y diseño de circuitos con amplificadores operacionales.",
     "Dificil"),
    (13,
     "El curso de Proyecto Eléctrico es una parte crucial del bachillerato en ingeniería eléctrica, 
      diseñado para integrar y aplicar estrategias de diseño, investigación y solución de problemas 
      en este campo y áreas relacionadas. Se distingue por su enfoque integral y su conexión directa 
      con el proceso formativo del estudiante, aprovechando los conocimientos previamente adquiridos. 
      Este curso facilita la convergencia de habilidades y conocimientos, preparando a los estudiantes 
      para enfrentar desafíos y aprovechar oportunidades tanto académicas como profesionales en el 
      desarrollo de proyectos eléctricos.",
     "Dificil"),
    (14,
     "El curso de Teoría de la Probabilidad cubre desde conceptos básicos como definiciones y teoría de 
      conjuntos, hasta variables aleatorias (discretas y continuas), distribuciones de probabilidad, 
      procesos estocásticos (estacionaridad, autocorrelación, espectro de densidad de potencia) y cadenas 
      de Markov (tipos, aplicaciones en análisis de señales y sistemas). Está diseñado para estudiantes de 
      ingeniería eléctrica interesados en aplicaciones prácticas como modulación digital, estimación de 
      estados con ruido y filtros de Kalman.",
     "Medio"),
    (15,
     "El curso teórico aborda la responsabilidad en el ejercicio profesional, destacando su relevancia 
      social y económica. Se enfoca en la ética como fundamento principal, explorando los principios éticos 
      que guían la conducta profesional a través de la ética profesional y la deontología.",
     "Facil");
SELECT * FROM `Tarea06_db`.Descripciones;



-- 4.1. Insercion de 2 Cursos propuestos por el estudiante
INSERT INTO `Tarea06_db`.Cursos(sigla, nombre, semestre, creditos)
VALUES("IE-1010", "Principios de diseño analogico", NULL, 4),
	  ("IE-1011", "Diseño digital", NULL, 4),
      ("IE-0523", "Circuitos digitales II", "VI", "3"),
      ("IE-0311", "Dispositivos Semiconductores", "VI", "3");
SELECT * FROM `Tarea06_db`.Cursos;


-- 4.2. Actualizar la Tabla de Requisitos
INSERT INTO `Tarea06_db`.Requisitos(id_curso, id_curso_requisito)
VALUES ((SELECT id_curso FROM `Tarea06_db`.Cursos WHERE nombre="Principios de diseño analogico"), 
		(SELECT id_curso FROM `Tarea06_db`.Cursos WHERE nombre="Circuitos digitales II")),
	   ((SELECT id_curso FROM `Tarea06_db`.Cursos WHERE nombre="Principios de diseño analogico"), 
		(SELECT id_curso FROM `Tarea06_db`.Cursos WHERE nombre="Electronica II")),
       ((SELECT id_curso FROM `Tarea06_db`.Cursos WHERE nombre="Diseño digital"), 
		(SELECT id_curso FROM `Tarea06_db`.Cursos WHERE nombre="Circuitos digitales II")),
	   ((SELECT id_curso FROM `Tarea06_db`.Cursos WHERE nombre="Diseño digital"), 
		(SELECT id_curso FROM `Tarea06_db`.Cursos WHERE nombre="Dispositivos Semiconductores"));
SELECT * FROM `Tarea06_db`.Requisitos;


-- 4.3. Actualizar la Tabla de Descripciones
INSERT INTO `Tarea06_db`.Descripciones (id_curso, descripcion, dificultad)
VALUES
    (16,
     "Este curso abarca interfaces de E/S eléctricas y ópticas de alta velocidad, sistemas de 
      recuperación de reloj, transceptores RF, circuitos de recolección de energía, MEMS RF, 
      sensores activos y pasivos, circuitos de microondas, procesamiento de señales robusto, 
      diseño de circuitos analógicos de alto rendimiento con baja tensión, diagnóstico de fallos 
      en circuitos integrados de modo mixto analógico, gestión de energía y circuitos y sistemas biomédicos.",
     "Dificil"),
    (17, 
     "Este curso introductorio aborda los fundamentos de la lógica digital, los circuitos 
      digitales y los dispositivos programables. Su objetivo es proporcionar a los estudiantes 
      una comprensión de los elementos básicos de los sistemas digitales modernos y los métodos 
      para diseñar, simular y realizar dichos sistemas. El énfasis está en entender los fundamentos 
      del diseño digital a través de diferentes niveles de abstracción utilizando lenguajes de 
      descripción de hardware, y en desarrollar una perspectiva sólida para el diseño de sistemas 
      digitales complejos.", 
     "Dificil"),
	(18, 
     "El curso tiene como objetivo desarrollar habilidades para el diseño lógico de sistemas 
      digitales, con un enfoque principal en ASICs y aplicaciones en FPGAs y tarjetas impresas. 
      Los estudiantes aprenderán una metodología estructurada que parte de la descripción 
      jerárquica del sistema para crear circuitos digitales interconectados verificables y 
      sintetizables. Utilizando lenguajes como Verilog, podrán modelar sistemas conductualmente, 
      anticipando el rendimiento temporal, consumo de energía y otras características físicas. 
      Además, aprenderán a sintetizar y evaluar diferentes opciones de construcción tecnológica, 
      optimizando velocidad, eficiencia energética, coste y sostenibilidad ambiental.", 
     "Media"),
	(19, 
     "El curso cubre una amplia gama de temas en el diseño de circuitos integrados. 
      Inicia con la introducción y motivación del diseño de circuitos integrados, 
      seguido de ejemplos y repaso de MOSFET. Se abordan temas como compuertas CMOS, 
      fabricación de circuitos CMOS, teoría del MOSFET, características I-V, y efectos 
      no ideales. También se estudia la operación del inversor CMOS, niveles lógicos, 
      estimación de potencia y retraso, así como diseño de circuitos combinacionales y 
      elementos secuenciales como latches, flip-flops y memorias SRAM y DRAM. Finalmente, 
      se discuten consideraciones de cableado, modelos de interconexión, y distribución de 
      potencia y reloj en el diseño físico de circuitos integrados.", 
     "Media");
     
SELECT * FROM `Tarea06_db`.Descripciones;

